version: '2'
services:
  web:
    image: alexcheng/magento:1.8.1.0
    ports:
      - "80:80"
    links:
      - mysql
    env_file:
      - env
  mysql:
    image: mysql:5.6.23
    env_file:
      - env
